export const portfolioData = {
  personal: {
    name: "Nur Hasin Ahammad",
    firstName: "Nur Hasin",
    lastName: "Ahammad",
    title: "Software Engineer",
    subtitle: "Full-Stack Developer & Open Source Contributor",
    tagline: "I build clean, scalable software — from REST APIs to game engines.",
    location: "Dhaka, Bangladesh",
    phone: "+8801625614059",
    email: "nur.hasin.ahammad@gmail.com",
    available: true,
    links: {
      linkedin: "https://www.linkedin.com/in/nur-hasin",
      github: "https://github.com/nur-hasin",
      leetcode: "https://leetcode.com/u/nur-hasin/",
    },
  },
  stats: [
    { value: "3.71", label: "CGPA / 4.00", suffix: "" },
    { value: "4", label: "Major Projects", suffix: "" },
    { value: "6", label: "OSS Pull Requests", suffix: "+" },
    { value: "10,000", label: "Hacktoberfest Rank", suffix: "Top" },
  ],
  education: [
    {
      degree: "B.Sc. Computer Science & Engineering",
      major: "Major: Software Engineering",
      institution: "American International University-Bangladesh (AIUB)",
      location: "Dhaka, Bangladesh",
      period: "Jan 2023 – Jan 2027",
      gpa: "3.71 / 4.00",
      current: true,
    },
    {
      degree: "Higher Secondary Certificate (HSC)",
      major: "Science",
      institution: "Padma Govt. College",
      location: "Rajshahi, Bangladesh",
      period: "2021",
      gpa: "5.00 / 5.00",
      current: false,
    },
    {
      degree: "Secondary School Certificate (SSC)",
      major: "Science",
      institution: "Harimohan Govt. High School",
      location: "Chapainawabganj, Bangladesh",
      period: "2019",
      gpa: "4.83 / 5.00",
      current: false,
    },
  ],
  skills: {
    languages: ["C++", "Java", "C#", "Python", "JavaScript", "PHP", "TypeScript"],
    frameworks: ["React.js", "Next.js", "Node.js", "Express.js", "Bootstrap", "Tailwind CSS", ".NET", "OpenGL", "Swing"],
    databases: ["MongoDB", "MySQL"],
    tools: ["Git", "GitHub", "VS Code", "MS Office"],
    concepts: [
      "Data Structures & Algorithms",
      "Object-Oriented Programming",
      "Database Management Systems",
      "Computer Networking",
      "Operating Systems",
    ],
  },
  projects: [
    {
      name: "GoGrocery",
      emoji: "🛒",
      tagline: "Multi-role e-commerce ecosystem",
      period: "Oct – Dec 2025",
      tech: ["PHP", "MySQL", "REST API", "CSS Grid"],
      accentColor: "#059669",
      description:
        "A full-stack grocery platform with 5 distinct role-based dashboards — Admin, Manager, Shop, Customer, and Rider — each with dedicated workflows and access control.",
      highlights: [
        "Custom REST API decoupling frontend from server logic",
        "Asynchronous cart updates & real-time inventory tracking",
        "Secure session handling with role-based access control",
        "Responsive grid-based UI for all device sizes",
      ],
      github: "https://github.com/nur-hasin/go-grocery",
    },
    {
      name: "Maze Magnitude: Time Fractals",
      emoji: "🎮",
      tagline: "2D platformer engine from scratch",
      period: "Oct – Dec 2024",
      tech: ["C++", "OpenGL", "AABB Physics", "Audio"],
      accentColor: "#d97706",
      description:
        "A high-performance 2D platformer engine written in C++ with OpenGL — zero external game engine, fully custom physics, collision, and audio systems.",
      highlights: [
        "Manual memory allocation management for stability",
        "Custom AABB collision detection algorithms from scratch",
        "Synchronized game loop: rendering, physics & audio",
        "Multi-channel audio playback system",
      ],
      github: "https://github.com/nur-hasin/maze-magnitude-time-fractals",
    },
    {
      name: "Club Sphere",
      emoji: "⚽",
      tagline: "Enterprise ERP for club management",
      period: "Mar – May 2024",
      tech: ["C#", ".NET", "SQL", "Guna UI", "MVC"],
      accentColor: "#7c3aed",
      description:
        "A robust club management ERP system built strictly on MVC architecture in C# .NET, featuring modern WinForms UI and complex transfer market logic.",
      highlights: [
        "Guna UI integration for polished WinForms interface",
        "Transfer Market with real-time negotiation algorithms",
        "Budget deductions & contract lifecycle management",
        "Optimized SQL for players, coaches & ownership data",
      ],
      github: "https://github.com/nur-hasin/club-sphere",
    },
    {
      name: "Movie Buzz",
      emoji: "🎬",
      tagline: "Cinema booking with visual seat selection",
      period: "Oct – Dec 2023",
      tech: ["Java", "Swing", "File I/O"],
      accentColor: "#dc2626",
      description:
        "A standalone cinema booking app in Java Swing featuring a custom file-based persistence layer and a visual seat mapping algorithm.",
      highlights: [
        "Custom File I/O persistence replacing SQL overhead",
        "2D array-to-UI mapping for visual seat selection",
        "Dynamic admin-side showtime scheduling",
        "Automated ticket pricing calculation engine",
      ],
      github: "https://github.com/nur-hasin/movie-buzz",
    },
  ],
  experience: [
    {
      role: "Open Source Contributor",
      org: "Social Winter of Code (SWOC)",
      period: "Jan 2026 – Present",
      type: "Remote",
      active: true,
      highlights: [
        "Building and maintaining open-source repositories with project mentors",
        "Focused on scalable software architecture patterns",
        "Collaborative code reviews and structured version control workflows",
      ],
    },
    {
      role: "Open Source Contributor",
      org: "Elite Coders",
      period: "Jan 2026 – Present",
      type: "Remote",
      active: true,
      highlights: [
        "Developing portfolio-ready software in a structured virtual environment",
        "Applying industry-standard engineering practices under senior mentorship",
        "Building real-world open-source contributions with accountability",
      ],
    },
    {
      role: "Open Source Contributor",
      org: "Hacktoberfest 2025 (DigitalOcean)",
      period: "Oct 2025",
      type: "Remote",
      active: false,
      highlights: [
        "Fixed React.js component logic, CSS stacking contexts & overflow issues",
        "Built Pomodoro Timer & BMI Calculator using JavaScript and Chart.js",
        "Improved WCAG accessibility with semantic HTML improvements",
        "Shipped 6+ quality Pull Requests across a dedicated month of contribution",
      ],
    },
  ],
  achievements: [
    { title: "Top 10k Global", desc: "Hacktoberfest 2025", icon: "🌍" },
    { title: "Super Contributor", desc: "DigitalOcean Verified", icon: "⭐" },
    { title: "Holopin Badges", desc: "Open Source Verified", icon: "🏅" },
    { title: "CGPA 3.71 / 4.00", desc: "AIUB Academic Record", icon: "🎓" },
    { title: "HSC GPA 5.00 / 5.00", desc: "Perfect Score", icon: "📚" },
  ],
  certificates: [
    {
      title: "Hacktoberfest 2025 Completion",
      issuer: "DigitalOcean",
      date: "Oct 2025",
      image: "/certificates/cert1.jpg",
    },
    {
      title: "Super Contributor Badge",
      issuer: "DigitalOcean / Holopin",
      date: "2025",
      image: "/certificates/cert2.jpg",
    },
    {
      title: "Open Source Contribution",
      issuer: "SWOC",
      date: "2026",
      image: "/certificates/cert3.jpg",
    },
  ],
  video: {
    src: "/video/intro.mp4",
    poster: "/video/poster.jpg",
    title: "Introduction Video",
    duration: "1:18",
    resolution: "1080×1080",
  },
  references: [
    {
      name: "Prof. Dr. Dip Nandi",
      title: "Associate Dean, Faculty of Science & Technology",
      institution: "AIUB",
      email: "dip.nandi@aiub.edu",
    },
    {
      name: "Dr. Md. Abdullah-Al-Jubair",
      title: "Director, Department of Computer Science",
      institution: "AIUB",
      email: "abdullah@aiub.edu",
    },
  ],
};